Don't warn on enum switch if named values are exhaustive
dotnet/linker pull request #2795
Opened 2022-05-13 22:35 UTC by jtschuster

In some cases, it is helpful to only cover named values of enums in a switch without a catch-all at the bottom. Since the warning code is different for named and unnamed variants we can disable the unnamed variants warning. This way, if all named variants are accounted for without the catch-all and a new variant is added it will warn in that location.

2022-05-16 06:56 UTC, marek-safar requested changes

2022-05-16 06:56 UTC, marek-safar commented on .editorconfig
> +dotnet_diagnostic.CS8524.severity = none
I don't like disabling this globally. If there is a reason why the warning should be suppressed please use #pragma

2022-05-16 21:14 UTC, agocke commented
I agree with @marek-safar on this one. I think the real value from completeness checking is actually the warning: if the switch is not complete, a warning occurs. In this case, no warning would occur even if you're missing a legitimate case.

I think this should be fixed at the C# level (and I have a proposal for it somewhere), but in the meantime I would live with the warning. I would silence it in code by using a helper like,

```C#
var x = e switch
{
   E.Item1 => ...,
   E.Item2 => ...
   _ => throw ExceptionUtilities.UnexpectedValue(e)
};
```

2022-05-17 04:33 UTC, agocke commented
OK, I misunderstood -- turns out Roslyn generates two warnings here, one for switches which are incomplete due to not covering all integer enum cases, and one for everything else. So when we're silencing this warning, we're just silencing the enum-cast case.

I would be fine taking this change, but I also think there would be a good improvement here if we could use an analyzer to tage enums as not-convertible and suppress only in that case. I've made an analyzer to do this [https://www.nuget.org/packages/StaticCS/](https://www.nuget.org/packages/StaticCS/), I just need to figure out if we can reference it in the build.

2022-06-01 23:10 UTC, agocke approved these changes
This should be all fixed now. No need to disable the warning everywhere, but no warnings on "Closed" enums

2022-06-03 21:44 UTC, merged